version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pokedex
      - SPRING_DATASOURCE_USERNAME=pokedex_user
      - SPRING_DATASOURCE_PASSWORD=pokedex_password
    depends_on:
      - db
    networks:
      - pokedex-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pokedex
      - POSTGRES_USER=pokedex_user
      - POSTGRES_PASSWORD=pokedex_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pokedex-network

volumes:
  postgres_data:

networks:
  pokedex-network:
    driver: bridge 