spring:
  # Database Configuration for Development
  datasource:
    url: jdbc:postgresql://localhost:5432/pokedex
    driver-class-name: org.postgresql.Driver
    username: pokedex_user
    password: pokedex_password

  # JPA Configuration for Development
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging Configuration for Development
logging:
  level:
    com.nationalpokedex.api: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
